import type { PlatformCapabilityDefinition, PlatformCapabilityId } from "@/lib/impactos/types";

export const capabilityRegistry: PlatformCapabilityDefinition[] = [
  {
    id: "identity",
    name: "Identity",
    description: "Authentication, sessions, invites, and account lifecycle contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "governance",
    requiredFor: ["admin"],
  },
  {
    id: "permissions",
    name: "Permission Engine",
    description: "RBAC permission grants with future ABAC-compatible evaluation context.",
    status: "stable",
    version: "1.0.0",
    owner: "governance",
  },
  {
    id: "configuration",
    name: "Configuration Engine",
    description: "Deterministic effective configuration resolution and validation.",
    status: "stable",
    version: "1.0.0",
    owner: "core",
  },
  {
    id: "module-registry",
    name: "Module Registry",
    description: "Module metadata, lifecycle, dependencies, permissions, and availability.",
    status: "stable",
    version: "1.0.0",
    owner: "core",
    requiredFor: ["admin"],
  },
  {
    id: "edition-registry",
    name: "Edition Registry",
    description: "Edition manifests, defaults, compatibility, and version ownership.",
    status: "stable",
    version: "1.0.0",
    owner: "core",
    requiredFor: ["admin"],
  },
  {
    id: "navigation",
    name: "Navigation Resolver",
    description: "Builds navigation from configuration, module availability, permissions, and flags.",
    status: "stable",
    version: "1.0.0",
    owner: "core",
  },
  {
    id: "projects",
    name: "Projects Capability",
    description: "Platform contracts for project and program records.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["projects"],
  },
  {
    id: "knowledge",
    name: "Knowledge System",
    description: "Collections, taxonomy, review, lineage, retrieval, and permission-aware scope.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["knowledge", "assistant"],
    dependsOn: ["search"],
  },
  {
    id: "documents",
    name: "Documents Capability",
    description: "Document, evidence, template, approval, and attachment contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["documents"],
    dependsOn: ["search"],
  },
  {
    id: "reporting",
    name: "Reporting Capability",
    description: "Report assembly, review, approval, publishing, and export contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["reports"],
    dependsOn: ["workflow-runtime"],
  },
  {
    id: "maps",
    name: "Maps Capability",
    description: "Geographic context, sites, regions, assets, geocoding, and spatial layer contracts.",
    status: "beta",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["maps"],
  },
  {
    id: "ai-assistant",
    name: "AI Assistant",
    description: "Governed assistant product capability exposed through module contracts.",
    status: "beta",
    version: "1.0.0",
    owner: "intelligence",
    requiredFor: ["assistant"],
    dependsOn: ["ai-orchestration", "knowledge", "search", "audit"],
  },
  {
    id: "ai-orchestration",
    name: "AI Orchestration",
    description: "Assistant prompts, tools, retrieval, model policy, evaluations, and audit hooks.",
    status: "beta",
    version: "1.0.0",
    owner: "intelligence",
    requiredFor: ["assistant"],
  },
  {
    id: "automation",
    name: "Automation Capability",
    description: "Declarative automation contracts for triggers, conditions, actions, and approvals.",
    status: "internal-preview",
    version: "1.0.0",
    owner: "operations",
    requiredFor: ["workflows"],
    dependsOn: ["workflow-runtime"],
  },
  {
    id: "workflow-runtime",
    name: "Workflow Runtime",
    description: "Retryable workflow execution, approvals, handoffs, and run status contracts.",
    status: "internal-preview",
    version: "1.0.0",
    owner: "operations",
    requiredFor: ["workflows", "reports"],
  },
  {
    id: "audit",
    name: "Audit System",
    description: "Append-only sensitive event recording and review contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "governance",
  },
  {
    id: "notifications",
    name: "Notification System",
    description: "Alerts, digests, reminders, escalation, and delivery contracts.",
    status: "planned",
    version: "1.0.0",
    owner: "operations",
  },
  {
    id: "search",
    name: "Search",
    description: "Permission-aware full-text and semantic search contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Product, operating, assistant, integration, and workflow analytics contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "data",
    requiredFor: ["dashboard", "kpis"],
  },
  {
    id: "feature-flags",
    name: "Feature Flags",
    description: "Tenant, workspace, module, role, and user rollout contracts.",
    status: "stable",
    version: "1.0.0",
    owner: "core",
  },
];

export function getCapabilityById(capabilityId: PlatformCapabilityId) {
  return capabilityRegistry.find((capability) => capability.id === capabilityId);
}

export function listCapabilities(capabilityIds?: PlatformCapabilityId[]) {
  if (!capabilityIds) return capabilityRegistry;
  return capabilityRegistry.filter((capability) => capabilityIds.includes(capability.id));
}
