import {
  BarChart3,
  Bot,
  FileText,
  FolderKanban,
  Gauge,
  Home,
  Landmark,
  Map,
  Plug,
  ShieldCheck,
  Workflow,
} from "lucide-react";
import type {
  ImpactModuleDefinition,
  ImpactModuleId,
  PermissionAction,
  PermissionKey,
  PlatformCapabilityId,
} from "@/lib/impactos/types";

function permissions(moduleId: ImpactModuleId, actions: PermissionAction[]): Partial<Record<PermissionAction, PermissionKey>> {
  return actions.reduce(
    (result, action) => ({ ...result, [action]: `${moduleId}:${action}` as PermissionKey }),
    {} as Partial<Record<PermissionAction, PermissionKey>>,
  );
}

const baselineCapabilities: PlatformCapabilityId[] = ["permissions", "configuration", "navigation", "audit"];

export const coreModuleRegistry: ImpactModuleDefinition[] = [
  {
    id: "home",
    name: "Home",
    shortName: "Home",
    description: "Workspace overview, recent activity, priorities, and operating context.",
    status: "stable",
    version: "1.0.0",
    category: "workspace",
    icon: Home,
    requiredCapabilities: baselineCapabilities,
    permissions: permissions("home", ["view", "configure"]),
    defaultNavigationGroup: "operate",
  },
  {
    id: "dashboard",
    name: "Dashboard",
    shortName: "Dashboard",
    description: "KPIs, risks, progress, decisions, and operating signals.",
    status: "stable",
    version: "1.0.0",
    category: "workspace",
    icon: Gauge,
    requiredCapabilities: [...baselineCapabilities, "analytics"],
    permissions: permissions("dashboard", ["view", "configure", "export"]),
    defaultNavigationGroup: "measure",
  },
  {
    id: "projects",
    name: "Projects",
    shortName: "Projects",
    description: "Programs, initiatives, milestones, ownership, status, and risk.",
    status: "stable",
    version: "1.0.0",
    category: "data",
    icon: FolderKanban,
    requiredCapabilities: [...baselineCapabilities, "projects"],
    permissions: permissions("projects", ["view", "create", "edit", "delete", "configure"]),
    defaultNavigationGroup: "operate",
  },
  {
    id: "knowledge",
    name: "Knowledge",
    shortName: "Knowledge",
    description: "Curated organizational memory, collections, taxonomy, review, and reuse.",
    status: "stable",
    version: "1.0.0",
    category: "data",
    icon: Landmark,
    requiredCapabilities: [...baselineCapabilities, "knowledge", "search"],
    permissions: permissions("knowledge", ["view", "create", "edit", "approve", "configure"]),
    defaultNavigationGroup: "knowledge",
  },
  {
    id: "documents",
    name: "Documents",
    shortName: "Documents",
    description: "Files, evidence, templates, approvals, and attachments.",
    status: "stable",
    version: "1.0.0",
    category: "data",
    icon: FileText,
    requiredCapabilities: [...baselineCapabilities, "documents", "search"],
    permissions: permissions("documents", ["view", "create", "edit", "delete", "approve", "export", "configure"]),
    defaultNavigationGroup: "knowledge",
  },
  {
    id: "reports",
    name: "Reports",
    shortName: "Reports",
    description: "Report assembly, evidence linking, review, approval, publishing, and exports.",
    status: "stable",
    version: "1.0.0",
    category: "data",
    icon: BarChart3,
    requiredCapabilities: [...baselineCapabilities, "reporting", "workflow-runtime"],
    permissions: permissions("reports", ["view", "create", "edit", "approve", "publish", "export", "configure"]),
    defaultNavigationGroup: "measure",
  },
  {
    id: "kpis",
    name: "KPIs",
    shortName: "KPIs",
    description: "Metric definitions, targets, thresholds, evidence, and cadence.",
    status: "stable",
    version: "1.0.0",
    category: "data",
    icon: BarChart3,
    requiredCapabilities: [...baselineCapabilities, "analytics"],
    permissions: permissions("kpis", ["view", "create", "edit", "approve", "export", "configure"]),
    defaultNavigationGroup: "measure",
  },
  {
    id: "maps",
    name: "Maps",
    shortName: "Maps",
    description: "Geographic operating context, sites, regions, assets, and spatial layers.",
    status: "beta",
    version: "1.0.0",
    category: "data",
    icon: Map,
    requiredCapabilities: [...baselineCapabilities, "maps"],
    permissions: permissions("maps", ["view", "configure"]),
    defaultNavigationGroup: "measure",
  },
  {
    id: "assistant",
    name: "Assistant",
    shortName: "Assistant",
    description: "Governed AI interface scoped by permissions, knowledge, tools, and audit policy.",
    status: "beta",
    version: "1.0.0",
    category: "intelligence",
    icon: Bot,
    requiredCapabilities: [...baselineCapabilities, "ai-assistant", "ai-orchestration", "knowledge", "search"],
    permissions: permissions("assistant", ["view", "create", "configure"]),
    defaultNavigationGroup: "operate",
  },
  {
    id: "workflows",
    name: "Workflows",
    shortName: "Workflows",
    description: "Automations, approvals, reminders, handoffs, and retryable operating routines.",
    status: "internal-preview",
    version: "1.0.0",
    category: "workspace",
    icon: Workflow,
    requiredCapabilities: [...baselineCapabilities, "automation", "workflow-runtime"],
    permissions: permissions("workflows", ["view", "create", "edit", "approve", "configure", "admin"]),
    defaultNavigationGroup: "operate",
  },
  {
    id: "integrations",
    name: "Integrations",
    shortName: "Integrations",
    description: "Connector installations, sync status, provider scope, and credential ownership.",
    status: "internal-preview",
    version: "1.0.0",
    category: "integration",
    icon: Plug,
    requiredCapabilities: [...baselineCapabilities, "feature-flags"],
    permissions: permissions("integrations", ["view", "configure", "admin"]),
    defaultNavigationGroup: "configure",
  },
  {
    id: "admin",
    name: "Admin",
    shortName: "Admin",
    description: "Users, roles, configuration, audit, settings, and workspace governance.",
    status: "stable",
    version: "1.0.0",
    category: "governance",
    icon: ShieldCheck,
    requiredCapabilities: [...baselineCapabilities, "identity", "module-registry", "edition-registry"],
    permissions: permissions("admin", ["view", "configure", "admin"]),
    defaultNavigationGroup: "configure",
  },
];

export function getModuleById(moduleId: ImpactModuleId) {
  return coreModuleRegistry.find((module) => module.id === moduleId);
}

export function listModules(moduleIds?: ImpactModuleId[]) {
  if (!moduleIds) return coreModuleRegistry;
  return coreModuleRegistry.filter((module) => moduleIds.includes(module.id));
}
